project:
  version: 1.0
  code: sz
spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    locale: zh_CN
    time-zone: 'GMT+8'
    #为空或null也可参与序列化
    default-property-inclusion: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.158.96:3306/SZ?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 0zf!llj=N1b521
  redis:
    host: 124.223.158.96
    port: 6379
    password: youpassword
    connect-timeout: 1000
    lettuce:
      pool:
        enabled: true
        max-active: 20
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
    redis:
      use-key-prefix: true
      time-to-live: 1d
#监控
management:
  server:
    port: 22803
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /application

debug: false


#mybatis设置
mybatis:
  configuration:
    default-statement-timeout: 10
#分页设置
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false

#swagger生成API相关
swagger:
  #是否启用swagger，默认：true
  enabled: true
  title: 'A'
  description: 'A'
  #swagger扫描的基础包，默认：全扫描
  #需要处理的基础URL规则,默认：/**
  base-path: /**
  #需要排除的URL规则，默认：空
  exclude-path: /error, /ops/**
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    locale: zh_CN
    time-zone: 'GMT+8'
    #为空或null也可参与序列化
    default-property-inclusion: always


minio:
  # 是否启用Minio
  enable: true
  # Minio接入地址
  endpoint: http://124.223.158.96:9999
  # Minio AccessKey
  accessKey: admin
  # Minio SecretKey
  secretKey: fengyadong
  # Minio存储桶
  bucket: sz_subway
  # Minio对外访问地址
  gateway: http://124.223.158.96:9990